language: swift
osx_image: xcode12.2
xcode_project: gamebook.xcodeproj
xcode_scheme:
 - gamebook
 - CommonTests
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 11 Pro
script: xcodebuild -resolvePackageDependencies
git:
 submodules: false
before_install:
 - sed -i -e 's|git@github.com:|https://github.com/|' .gitmodules
 - git submodule update --force --init --recursive --remote
