language: swift
osx_image: xcode12.2
script:
 - set -o pipefail && xcodebuild clean -workspace "gamebook.xcworkspace" -scheme gamebook -destination "platform=iOS Simulator,name=iPhone 11 Pro" -derivedDataPath DerivedData build-for-testing | xcpretty --color --simple
