
language: swift
osx_image: xcode12.2
script:
 - xcodebuild -resolvePackageDependencies
 - set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "gamebook.xcworkspace" -scheme "gamebook" -destination "platform=iOS Simulator,OS=14.2,name=iPhone 11 Pro" clean test | xcpretty
