language: swift
osx_image: xcode12.2
xcode_project: gamebook.xcodeproj
xcode_scheme:
 - gamebook
 - Common
 - Core
 - User
 - Game
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro
git:
 submodules: false
before_install:
 - sed -i -e 's|git@github.com:|https://github.com/|' .gitmodules
 - git submodule update --init --recursive
