name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    env:
      SCHEME: "gamebook"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    runs-on: macOS-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: Fetch Pods
      run: pod install
    - name: Build application
      run: |
        set -o pipefail && xcodebuild clean -workspace "gamebook.xcworkspace" -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE" build-for-testing | xcpretty --color --simple
    - name: Upload products
      uses: actions/upload-artifact@v1
      with:
        name: Products
        path: DerivedData/Build/Products

  
