name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: ["OS=14.2,name=iPhone 11 Pro"]

    steps:
    - uses: actions/checkout@v2
    - name: iOS - ${{ matrix.destination }}
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "gamebook.xcodeproj" -scheme "gamebook" -destination "${{ matrix.destination }}" clean test | xcpretty
